// This file is generated by scripts/gen_frontend_protocol.py at 2025-07-29 23:34:07
// DO NOT MODIFY THIS FILE DIRECTLY OR YOUR CHANGES WILL BE OVERWRITTEN BY THE NEXT GENERATION.

export interface TokenRequest {
  token: string
}

export interface EmailRequest {
  email: string
}
