// This file is generated by scripts/gen_frontend_protocol.py at 2025-07-28 22:37:08
// DO NOT MODIFY THIS FILE DIRECTLY OR YOUR CHANGES WILL BE OVERWRITTEN BY THE NEXT GENERATION.

export interface TokenRequest {
  token: string;
};

export interface SignUpCredentialsRequest {
  display_name: string;
  email: string;
  password: string;
};

export interface SignInCredentialsRequest {
  email: string;
  password: string;
};
