// This file is generated by scripts/gen_frontend_protocol.py at 2025-07-29 23:34:07
// DO NOT MODIFY THIS FILE DIRECTLY OR YOUR CHANGES WILL BE OVERWRITTEN BY THE NEXT GENERATION.

export interface GetTokenResponse {
  token: string
}

export interface GetThirdPartyTokensResponse {
  huggingface: string
  openai: string
  wandb: string
}

export interface VerifyTokenResponse {
  valid: boolean
  reason: string
}

export interface GetServerStatusResponse {
  status: string
  ip_address: string
  port: number
  hostname: string
}

export interface Session {
  user_id: string
  user_email: string
  email_confirmed: boolean
  access_token: string
  refresh_token: string
  expires_at: number
}

export interface SessionResponse {
  session: Session
}

export interface UserProfile {
  display_name: string
}
